esphome:
  name: voice-assist-circle
  friendly_name: Voice Assist Circle


esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3  
  flash_size: 16MB
  framework:
    type: esp-idf

    version: recommended
    sdkconfig_options:
      # ESP32-S3 N16R8
      CONFIG_ESP32_S3_BOX_BOARD: "y"
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB:      "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B:  "y"
      CONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST: "y"
      CONFIG_BT_BLE_DYNAMIC_ENV_MEMORY: "y"
      CONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC: "y"
      CONFIG_MBEDTLS_SSL_PROTO_TLS1_3: "y" 

psram:
  mode: octal
  speed: 80MHz

# Enable logging
logger:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


# Enable Home Assistant API
api:
  on_client_connected:
        then:
          - delay: 500ms
          - light.turn_off: led_circle
          - micro_wake_word.start:
  on_client_disconnected:
        then:
          - voice_assistant.stop: 




###############################################################################################################################

output:
  - platform: gpio
    pin: 
      number: GPIO01
      allow_other_uses: true
    id: set_low_speaker  # Prevents popping on speaker start

audio_file:
  - id: alert_sound
    file:
      type: local
      path: "audio/pop.mp3"

i2s_audio:
  - id: mic_i2s
    i2s_lrclk_pin: GPIO04  ###  WS
    i2s_bclk_pin: GPIO05 ###  SCK

  - id: spk_i2s
    i2s_lrclk_pin: GPIO06 ## LRC 
    i2s_bclk_pin: GPIO07 ## BCLK

microphone:
  - platform: i2s_audio
    id: mic
    i2s_audio_id: mic_i2s
    adc_type: external        
    i2s_din_pin: GPIO16 ### SD
    channel: right  
    pdm: false

speaker:
  - platform: i2s_audio
    id: big_speaker
    i2s_audio_id: spk_i2s
    i2s_dout_pin: 
      number: GPIO01
      allow_other_uses: true
    dac_type: external
    channel: stereo
 

  - platform: mixer
    id: mixer_speaker_id
    output_speaker: big_speaker
    num_channels: 2
    source_speakers:
      - id: announcement_spk_mixer_input
      - id: media_spk_mixer_input

  - platform: resampler
    id: media_spk_resampling_input
    output_speaker: media_spk_mixer_input

  - platform: resampler
    id: announcement_spk_resampling_input
    output_speaker: announcement_spk_mixer_input

media_player:
   - platform: speaker
     id: esps3_media_player
     name: VA Circle Media Player

     announcement_pipeline:
       speaker: announcement_spk_resampling_input 
       num_channels: 1
       format: MP3

     media_pipeline:
       speaker: media_spk_resampling_input
       format: MP3
       num_channels: 2

     on_announcement:
       - logger.log: "** MP Announcing! ** "
       - light.turn_off: led_circle  
       - delay: 50ms         
       - light.turn_on:
           id: led_circle           
           brightness: 90%
           effect: "Talking Swirl"

     on_play:
       - logger.log: "** MP Playback started! **"   
       - delay: 150ms             
       - light.turn_on:
           id: led_circle           
           red: 100%
           green: 80%
           blue: 60%
           brightness: 50%
           effect: "Twinkly"

     on_pause:            
       - logger.log: "** MP Playback PAUSED! ** "
       - light.turn_off: led_circle

     on_idle:
       - logger.log: "** MP Playback finished! ** "
       - light.turn_off: led_circle







################################################################################################################################

voice_assistant:
  id: assist
  microphone: mic
  micro_wake_word: mww
  noise_suppression_level: 2
  auto_gain: 31dBFS
  volume_multiplier: 3.0
  media_player: esps3_media_player  

  on_error:
    - logger.log: "** VA ERROR **"    
    - micro_wake_word.start:  
    - delay: 1s      
    - light.turn_on:
        id: led_circle           
        red: 70%
        green: 0%
        blue: 0%
        brightness: 40%
        effect: "Error Swirl"
    - delay: 3s
    - light.turn_off:
        id: led_circle 


  on_end:
    - logger.log: "** VA END **"        
    - light.turn_off: led_circle
    - wait_until:
        not:
          voice_assistant.is_running:
    - micro_wake_word.start:      



  on_stt_end:
    - logger.log: "** STT END **"
    - light.turn_off: led_circle    

  on_tts_start:
    - logger.log: "** TTS START **"   





###############################################################################################################################

switch:

  - platform: restart
    name: "Restart Device"

  - platform: template
    id: mute
    name: mute
    optimistic: true

    on_turn_on: 
      - micro_wake_word.stop:
      - voice_assistant.stop:
      - light.turn_on:
          id: led_circle           
          red: 60%
          green: 0%
          blue: 0%
          brightness: 40%
          effect: "Fast Pulse" 
      - delay: 2s
      - light.turn_off:
          id: led_circle

    on_turn_off:
      - micro_wake_word.start:
      - light.turn_on:
          id: led_circle           
          red: 0%
          green: 100%
          blue: 20%
          brightness: 60%
          effect: "Single Scan"
      - delay: 3s
      - light.turn_off:
          id: led_circle 



 


###############################################################################################################################

micro_wake_word:
  id: mww
  microphone:
    microphone: mic
    channels: 0
    gain_factor: 4
  vad:
  models:
    - model: okay_nabu
      id: okay_nabu_model
    - model: hey_jarvis
      id: hey_jarvis_model
    - model: alexa
      id: alexa
    - model: "https://raw.githubusercontent.com/esphome/micro-wake-word-models/refs/heads/main/models/v2/experiments/okay_computer.json"
      id: okay_computer
    - model: "https://raw.githubusercontent.com/esphome/micro-wake-word-models/refs/heads/main/models/v2/experiments/hey_home_assistant.json"
      id: hey_home_assistant


  on_wake_word_detected:
    - logger.log: "** WAKE WORD DETECTED**"       
    - voice_assistant.start:
        wake_word: !lambda return wake_word;

    - media_player.speaker.play_on_device_media_file:
        media_file: alert_sound
        announcement: False
    - delay: 450ms    
    - light.turn_off: led_circle                    
    - delay: 50ms        
    - light.turn_on:
        id: led_circle           
        effect: "Listening Swirl"
        brightness: 90%

light:
  - platform: esp32_rmt_led_strip
    id: led_circle
    rgb_order: GRB
    pin: GPIO48
    num_leds: 25
    chipset: ws2812
    name: "light Ring"

    effects:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.45s
          update_interval: 0.45s
          min_brightness: 0%
          max_brightness: 50%
          
      - pulse:
          name: "Slow Pulse"
          transition_length: 2.0s
          update_interval: 2.0s
          min_brightness: 0%
          max_brightness: 100%

      - pulse:
          name: "V Fast Pulse"
          transition_length: 0.25s
          update_interval: 0.25s
          min_brightness: 0%
          max_brightness: 100%

      - random:
          name: "Random Colors"
          transition_length: 1s
          update_interval: 2s

      - addressable_color_wipe:
          name: "Listening Swirl"
          colors:
            - red: 0%
              green: 80%
              blue: 80%
              num_leds: 10
              gradient: true
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 14            
          add_led_interval: 60ms
          reverse: false

      - addressable_color_wipe:
          name: Talking Swirl
          colors:
            - red: 50%
              green: 0%
              blue: 80%
              num_leds: 12
              gradient: true
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 12             
          add_led_interval: 70ms
          reverse: True

      - addressable_color_wipe:
          name: Error Swirl
          colors:
            - red: 60%
              green: 0%
              blue: 0%
              num_leds: 14
              gradient: true
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 10             
          add_led_interval: 50ms
          reverse: True

      - addressable_color_wipe:
          name: Timer
          colors:
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 1
              gradient: true
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 23            
          add_led_interval: 1000ms
          reverse: false

      - flicker:
          name: Flicker Effect
          alpha: 95%
          intensity: 1.5%

      - addressable_scan:
          name: Single Scan
          move_interval: 30ms
          scan_width: 1

      - addressable_rainbow:
          name: Rainbow Effect
          speed: 12
          width: 24

      - addressable_twinkle:
          name: Twinkly
          twinkle_probability: 5%
          progress_interval: 4ms
